import type { Metadata } from 'next'
import './globals.css'
import { AppProviders } from '@/components/app-providers'
import { AppLayout } from '@/components/app-layout'
import { Inter, Abril_Fatface, Kalam } from 'next/font/google'
import React from 'react'

export const metadata: Metadata = {
  title: 'MeBlog',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
  // More links...
  { label: 'Home', path: '/' },
  { label: 'Account', path: '/account' },
  { label: 'Basic Program', path: '/basic' },
]

const inter = Inter({ subsets: ['latin'] })
const abrilFatface = Abril_Fatface({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-abril-fatface'
})
const kalam = Kalam({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-kalam'
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${abrilFatface.variable} ${kalam.variable}`} suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <AppProviders>
          <AppLayout links={links}>{children}</AppLayout>
        </AppProviders>
      </body>
    </html>
  )
}

// Patch BigInt so we can log it using JSON.stringify without any errors
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}